name: Release
on:
  push:
    branches:
    - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      with:
        version: v3.10.1 # Also update in lint-and-test.yaml

    - name: Configure Git
      run: |
        git config user.name "Muhammad Nur Faza"
        git config user.email "gofar222@gmail.com"
    
    - name: Add dependency chart repos
      run: |
        helm repo add testing https://pasasageyo18.github.io/testing/

    - name: Fetch current Chart Index
      run: |
        git checkout origin/gh-pages index.yaml

    # - name: Import GPG key
    #   run: |
    #     IFS=""
    #     echo "$PGP_PRIVATE_KEY" | gpg --dearmor > $HOME/secring.gpg
    #     echo "$PGP_PASSPHRASE" > $HOME/passphrase.txt

    #     # Tell chart-releaser-action where to find the key and its passphrase
    #     echo "CR_KEYRING=$HOME/secring.gpg" >> "$GITHUB_ENV"
    #     echo "CR_PASSPHRASE_FILE=$HOME/passphrase.txt" >> "$GITHUB_ENV"
    #   env:
    #     PGP_PRIVATE_KEY: "${{ secrets.PGP_PRIVATE_KEY }}"
    #     PGP_PASSPHRASE: "${{ secrets.PGP_PASSPHRASE }}"

    - name: Release charts
      uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to GHCR
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push chart to GHCR
      run: |
        shopt -s nullglob
        for pkg in .cr-release-packages/*.tgz; do
          if [ -z "${pkg:-}" ]; then
            break
          fi
          helm push "${pkg}" oci://ghcr.io/${{ github.repository }}
        done