name: Release
on:
  push:
    branches:
    - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Set up Helm Chart
      uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Add dependency chart repos
      run: |
        helm repo add dandydeveloper https://dandydeveloper.github.io/charts/

    - name: Fetch current Chart Index
      run: |
        git checkout origin/gh-pages index.yaml

    - name: Import GPG key
      run: |
        echo "${{ secrets.PGP_PRIVATE_KEY }}" | gpg --dearmor --output ./keyring.gpg
        echo "${{ secrets.PGP_PASSPHRASE }}" >> ./passphrase-file.txt

    - name: Release charts
      uses: helm/chart-releaser-action@v1.6.0
      with:
        config: "./.github/configs/cr.yaml"
      env:
        CR_KEY: Muhammad Nur Faza <gofar222@gmail.com>
        CR_KEYRING: keyring.gpg
        CR_PASSPHRASE_FILE: passphrase-file.txt
        CR_SIGN: true
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}