name: Release
on:
  push:
    branches:
    - main
    paths:
    - charts/**
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Import GPG key
      run: |
        echo $HOME/
        echo "${{ secrets.PGP_PRIVATE_KEY }}" | gpg --dearmor --output /home/runner/.gnupg/pubring.gpg
        echo "${{ secrets.PASSPHRASE }}" > passphrase-file.txt

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release charts
      uses: helm/chart-releaser-action@v1.4.1
      with:
        config: "./.github/configs/cr.yaml"
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}